export enum EFontSize {
  FontSizeXS = 'XS',
  FontSizeSM = 'SM',
  FontSize = '',
  FontSizeLG = 'Lg',
  FontSizeXl = 'Xl',
  FontSize2XL = '2XL',
  FontSize3XL = '3XL',
  FontSize4XL = '4XL',
  FontSize5XL = '5XL',
  FontSize6XL = '6XL',
  FontSize7XL = '7XL',
  FontSize8XL = '8XL',
  FontSize9XL = '9XL',
}
